### ISSUE TITLE
NuGet package version 1.0.8 for HouseofCat.RabbitMQ.Services

### ISSUE THREAD

**Issue by tiggerite** [houseofcat/RabbitMQ.Dataflows#12]
Unfortunately the current one in NuGet is 1.0.7 and still has the old Options class, which is now RabbitOptions in 1.0.8+. Please release this one too :) (I guess a new version for all the RabbitMQ packages would be best, to prevent any chance of mismatched RabbitMQ main versions?)

**Comment by tristan-hyams** [comment]
Should be resolved with all our good work.

**Comment by tiggerite** [comment]
Don't want to open a new issue for this, but I've noticed the NuGet package for HouseofCat.RabbitMQ.Dataflows is pretty old (1.0.2) and using an equally old HouseofCat.RabbitMQ (1.0.4). Could it be published too or is it too much work in progress?
