### ISSUE TITLE
Update RabbitMQ.Client to 6.2.4

### ISSUE THREAD

**Issue by tiggerite** [houseofcat/RabbitMQ.Dataflows#40]
It contains some important bug fixes, especially one around auto recovery. Also would be a good time for a NuGet release (hint hint ;))

**Comment by tristan-hyams** [comment]
I will see what I can do over this weekend.

**Comment by tristan-hyams** [comment]
@tiggerite Publishing this today.

**Comment by tiggerite** [comment]
You have a new PR now too :) thanks for publishing it, 2.0.0 is great, especially targeting NET 6.
