### ISSUE TITLE
Move HouseofCat.RabbitMQ.Client logic from RabbitMQ.Client namespace to HouseofCat.RabbitMQ.Client

### ISSUE THREAD

**Issue by curtisy1** [houseofcat/RabbitMQ.Dataflows#6]
Currently, the namespace used in HouseofCat.RabbitMQ.Client is the same as in the original RabbitMQ.Client nuget package. However this could be a bit inconvenient for people with other libraries in place that have the official client as transient dependency.

Suppose we have a use case where we need to access the IModel property to manually Ack/NAck using something like the following:
```
private IModel model;
private async Task AssignModel() {
    var channelHost = await rabbitService.ChannelPool.GetAckChannelAsync().ConfigureAwait(false);
    model = channelHost.GetChannel();
}

private void AckWithMultipleEnabled(ulong deliveryTag) {
    model.BasicAck(deliveryTag, true);
}

// Repeat the above with all NAck and Ack variations
```

Since IModel exists bot in HouseofCat.RabbitMQ.Client and RabbitMQ.Client under the same namespace, the type of IModel is ambigious.

To prevent this I propose putting the implementation in HouseofCat.RabbitMQ.Client into a seperate HouseofCat.RabbitMQ.Client namespace so users have the possibility of having both libraries installed without conflict

**Comment by tristan-hyams** [comment]
They should not be used together and its that way to allow users to test replacing their dependency with this one without changing code. If you had a library that used the official client, you would change that library's dependency to this one - if at all. Alternatively, you could pulled down HouseofCat.RabbitMQ and switch it's dependency to the official one and compile that.

Based on release 6.1 and 7.0 proposals from Pivotal, I am not sure I will continue maintaining this client - I don't necessarily need to fix some bizarre things they used to do anymore.

**Comment by curtisy1** [comment]
While I understand this decision, it is highly inconvenient because it prevents me from using this RabbitMQ library at all.

I'll close this and check back in a while to see if the conflict still exists.

**Comment by tristan-hyams** [comment]
@curtisy1 check out the next upcoming release, I am switching to official 6.2 client. Then your library can update with this.
